# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 11:01
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAO_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aao_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'AAO',
                'verbose_name_plural': 'AAOs',
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': "Block's",
            },
        ),
        migrations.CreateModel(
            name='Dealer_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('license_num', models.CharField(blank=True, max_length=255)),
                ('company_type', models.CharField(choices=[('private', 'PRIVATE'), ('pacs', 'PACS')], max_length=7)),
                ('dealer_name', models.CharField(max_length=255)),
                ('contact_num', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('address', models.TextField(blank=True, max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 12, 7, 11, 1, 35, 553163))),
                ('dealer_pincode', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(6)])),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
            },
        ),
        migrations.CreateModel(
            name='DealerDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_collected', models.DateField()),
                ('chk', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(db_column='Dealer_Registration_id', on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration')),
            ],
            options={
                'verbose_name': 'Dealer Demand',
                'verbose_name_plural': 'Dealer Demands',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('dist_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': "District's",
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('suggestion', models.TextField(max_length=1650)),
            ],
            options={
                'verbose_name': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Mobnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobnum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'Mobile Number',
                'verbose_name_plural': 'Mobile numbers',
            },
        ),
        migrations.CreateModel(
            name='Panchayats',
            fields=[
                ('panchayat_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
            ],
            options={
                'verbose_name': 'Panchayat',
                'verbose_name_plural': 'Panchayats',
            },
        ),
        migrations.CreateModel(
            name='Pilotplots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('contact_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
                ('panchayat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Panchayats')),
            ],
            options={
                'verbose_name': 'Pilot Plots',
            },
        ),
        migrations.CreateModel(
            name='SPO',
            fields=[
                ('spo', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'SPO',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveIntegerField()),
                ('date_wn_available', models.DateField()),
                ('check', models.BooleanField()),
                ('dealer_shop', models.ForeignKey(db_column='Dealer_Registration_id', on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='STRAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='STRVCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_short_code', models.CharField(max_length=255)),
                ('category_description', models.TextField(max_length=650)),
                ('image', models.ImageField(upload_to='static/imgs/uploaded/category')),
            ],
            options={
                'verbose_name': 'STRV Category',
                'verbose_name_plural': 'STRV Category',
            },
        ),
        migrations.CreateModel(
            name='STRVVariety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=255)),
                ('variety_code', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=650)),
                ('duration_in_days', models.CharField(max_length=20)),
                ('suitable_land_type', models.CharField(max_length=200)),
                ('plant_height', models.CharField(max_length=20)),
                ('grain_type', models.CharField(max_length=255)),
                ('yield_in_tonne', models.CharField(max_length=20)),
                ('yield_advantage', models.CharField(max_length=50)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVCategory')),
            ],
            options={
                'verbose_name': 'STRV Variety',
                'verbose_name_plural': 'STRV Varieties',
            },
        ),
        migrations.CreateModel(
            name='Varietynew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VAW_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAW_name', models.CharField(max_length=255)),
                ('VAW_contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
                ('panchayat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Panchayats')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States')),
            ],
            options={
                'verbose_name': 'VAW',
                'verbose_name_plural': 'VAWs',
            },
        ),
        migrations.CreateModel(
            name='VAWDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety2', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date_collected', models.DateField(default=datetime.datetime(2017, 12, 7, 11, 1, 35, 558216))),
                ('check', models.BooleanField()),
                ('variety_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety')),
                ('vaw', models.ForeignKey(db_column='VAW_Registration_id', on_delete=django.db.models.deletion.CASCADE, to='Masters.VAW_Registration')),
            ],
            options={
                'verbose_name': 'VAW-Demand',
                'verbose_name_plural': 'VAW-Demands',
            },
        ),
        migrations.CreateModel(
            name='Vawmobnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaw_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'VawMobile',
                'verbose_name_plural': 'VawMobile Numbers',
            },
        ),
        migrations.CreateModel(
            name='ViewDealerlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
            ],
        ),
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('village_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
                ('panchayat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Panchayats')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
            },
        ),
        migrations.AddField(
            model_name='vawdemand',
            name='village_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Villages'),
        ),
        migrations.AddField(
            model_name='stravailability',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variety_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety'),
        ),
        migrations.AddField(
            model_name='pilotplots',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety'),
        ),
        migrations.AddField(
            model_name='pilotplots',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Villages'),
        ),
        migrations.AddField(
            model_name='panchayats',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='districts',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='dealerdemand',
            name='variety_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety'),
        ),
        migrations.AddField(
            model_name='dealer_registration',
            name='dealer_spo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.SPO'),
        ),
        migrations.AddField(
            model_name='dealer_registration',
            name='dist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AddField(
            model_name='dealer_registration',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='blocks',
            name='dist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AddField(
            model_name='blocks',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='aao_registration',
            name='block_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks'),
        ),
        migrations.AddField(
            model_name='aao_registration',
            name='dist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AddField(
            model_name='aao_registration',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
    ]
