# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 12:35
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAO_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aao_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'AAO',
                'verbose_name_plural': 'AAO Registrations',
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Blocks List',
                'verbose_name_plural': "Block's List",
            },
        ),
        migrations.CreateModel(
            name='Dealer_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('licence_num', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('private', 'PRIVATE'), ('pacs', 'PACS')], max_length=7)),
                ('dealer_name', models.CharField(max_length=255)),
                ('contact_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('address', models.TextField(max_length=255)),
                ('dealer_spo', models.CharField(choices=[('spo1', 'SPO 1'), ('spo2', 'SPO 2'), ('spo3', 'SPO 3')], max_length=5)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 12, 35, 14, 268872))),
                ('dealer_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(6)])),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealer Registrations',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_collected', models.DateField()),
                ('chk', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dealer Demand',
                'verbose_name_plural': 'Dealer Demands',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'District Names List',
                'verbose_name_plural': "District's List",
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('suggestion', models.TextField(max_length=1650)),
            ],
            options={
                'verbose_name': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Mobnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobnum', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'Mobile Number',
                'verbose_name_plural': 'Mobile numbers',
            },
        ),
        migrations.CreateModel(
            name='Panchayats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_name', models.CharField(max_length=100)),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
            ],
            options={
                'verbose_name': 'Panchayat List',
                'verbose_name_plural': 'Panchayats',
            },
        ),
        migrations.CreateModel(
            name='Pilotplots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
                ('panchayat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Panchayats')),
            ],
            options={
                'verbose_name': 'Pilot Plots',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'States List',
                'verbose_name_plural': 'States Lists',
            },
        ),
        migrations.CreateModel(
            name='STRVCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_short_code', models.CharField(max_length=255)),
                ('category_description', models.CharField(max_length=650)),
                ('image', models.ImageField(upload_to='pics')),
            ],
            options={
                'verbose_name': 'STRV Category',
                'verbose_name_plural': 'STRV Category',
            },
        ),
        migrations.CreateModel(
            name='STRVVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=255)),
                ('variety_code', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=650)),
                ('duration_in_days', models.PositiveIntegerField()),
                ('suitable_land_type', models.CharField(max_length=200)),
                ('plant_height', models.PositiveIntegerField()),
                ('grain_type', models.CharField(max_length=255)),
                ('yield_in_tonne', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'STRV Variety',
                'verbose_name_plural': 'STRV Variety',
            },
        ),
        migrations.CreateModel(
            name='VAW_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAW_name', models.CharField(max_length=255)),
                ('VAW_contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
                ('panchayat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Panchayats')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States')),
            ],
            options={
                'verbose_name': 'VAW',
                'verbose_name_plural': 'VAW Registrations',
            },
        ),
        migrations.CreateModel(
            name='VAWDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_collected', models.DateField(default=datetime.datetime(2017, 11, 1, 12, 35, 14, 273078))),
                ('check', models.BooleanField(default=True)),
                ('strv_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety')),
            ],
            options={
                'verbose_name': 'VAW-Demand',
                'verbose_name_plural': 'VAW-Demands',
            },
        ),
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks')),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts')),
                ('panchayat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Panchayats')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States')),
            ],
            options={
                'verbose_name': 'Villages List',
                'verbose_name_plural': 'Villages...',
            },
        ),
        migrations.AddField(
            model_name='vawdemand',
            name='village_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Villages'),
        ),
        migrations.AddField(
            model_name='panchayats',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='districts',
            name='state_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='demand',
            name='strv_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety'),
        ),
        migrations.AddField(
            model_name='dealer_registration',
            name='dist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AddField(
            model_name='dealer_registration',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='blocks',
            name='dist_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AddField(
            model_name='blocks',
            name='state_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AddField(
            model_name='aao_registration',
            name='block_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Blocks'),
        ),
        migrations.AddField(
            model_name='aao_registration',
            name='dist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AddField(
            model_name='aao_registration',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
    ]
