# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 12:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vawmobnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaw_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'VawMobile',
                'verbose_name_plural': 'VawMobile Numbers',
            },
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 12, 42, 9, 897671)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 12, 42, 9, 902371)),
        ),
    ]
