# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 11:16
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aao_registration',
            options={'verbose_name': 'AAO', 'verbose_name_plural': 'AAOs'},
        ),
        migrations.AlterModelOptions(
            name='blocks',
            options={'verbose_name': 'Block', 'verbose_name_plural': "Block's"},
        ),
        migrations.AlterModelOptions(
            name='dealer_registration',
            options={'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.AlterModelOptions(
            name='districts',
            options={'verbose_name': 'District', 'verbose_name_plural': "District's"},
        ),
        migrations.AlterModelOptions(
            name='panchayats',
            options={'verbose_name': 'Panchayat', 'verbose_name_plural': 'Panchayats'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='strvvariety',
            options={'verbose_name': 'STRV Variety', 'verbose_name_plural': 'STRV Varieties'},
        ),
        migrations.AlterModelOptions(
            name='vaw_registration',
            options={'verbose_name': 'VAW', 'verbose_name_plural': 'VAWs'},
        ),
        migrations.AlterModelOptions(
            name='villages',
            options={'verbose_name': 'Village', 'verbose_name_plural': 'Villages'},
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='strv_variety',
            new_name='variety_name',
        ),
        migrations.RenameField(
            model_name='vawdemand',
            old_name='strv_variety',
            new_name='variety_name',
        ),
        migrations.RemoveField(
            model_name='blocks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='panchayats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='states',
            name='id',
        ),
        migrations.RemoveField(
            model_name='strvvariety',
            name='id',
        ),
        migrations.RemoveField(
            model_name='villages',
            name='id',
        ),
        migrations.AlterField(
            model_name='blocks',
            name='block_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='dist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Districts'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='contact_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 4, 11, 15, 55, 562361)),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='dealer_pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='dealer_spo',
            field=models.CharField(blank=True, choices=[('spo1', 'SPO 1'), ('spo2', 'SPO 2'), ('spo3', 'SPO 3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='licence_num',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='districts',
            name='dist_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='districts',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.States'),
        ),
        migrations.AlterField(
            model_name='panchayats',
            name='panchayat_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='state_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strvcategory',
            name='image',
            field=models.ImageField(upload_to='static/imgs/uploaded/category'),
        ),
        migrations.AlterField(
            model_name='strvvariety',
            name='variety_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='check',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 4, 11, 15, 55, 566352)),
        ),
        migrations.AlterField(
            model_name='villages',
            name='village_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
