# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_auto_20171106_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='strvvariety',
            name='id',
            field=models.AutoField(default=1, primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 12, 22, 5, 101606)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 12, 22, 5, 105935)),
        ),
    ]
