# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_auto_20171105_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strvcategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 12, 3, 33, 833698)),
        ),
        migrations.AlterField(
            model_name='strvcategory',
            name='category_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 12, 3, 33, 837970)),
        ),
    ]
