# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_auto_20171219_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 11, 35, 2, 41662)),
        ),
        migrations.AlterField(
            model_name='pilotplots',
            name='village',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 12, 28, 11, 35, 2, 46649)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='village_name',
            field=models.CharField(max_length=255),
        ),
    ]
