# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 06:59
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_auto_20171104_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveIntegerField()),
                ('date_wn_available', models.DateField()),
                ('variety_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.RenameModel(
            old_name='Demand',
            new_name='DealerDemand',
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='contact_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 6, 59, 42, 761529)),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='dealer_pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='dealer_spo',
            field=models.CharField(choices=[('spo1', 'SPO 1'), ('spo2', 'SPO 2'), ('spo3', 'SPO 3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='licence_num',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 6, 59, 42, 765509)),
        ),
    ]
