# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_auto_20171105_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 12, 6, 27, 260893)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 12, 6, 27, 265170)),
        ),
    ]
