# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_auto_20171117_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='check',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 6, 53, 11, 413349)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 6, 53, 11, 418340)),
        ),
    ]
