# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_auto_20171106_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 12, 39, 16, 665355)),
        ),
        migrations.AlterField(
            model_name='strvvariety',
            name='variety_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 12, 39, 16, 669648)),
        ),
    ]
