# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 08:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_auto_20171105_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPO',
            fields=[
                ('spo', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'SPO',
            },
        ),
        migrations.RemoveField(
            model_name='dealer_registration',
            name='licence_num',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='dealer_registration',
            name='license_num',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='contact_num',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 8, 54, 26, 346072)),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='dealer_pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='dealer_spo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.SPO'),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='variety_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Masters.STRVVariety'),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 8, 54, 26, 350229)),
        ),
    ]
