# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_auto_20171105_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strvvariety',
            name='id',
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 3, 14, 481436)),
        ),
        migrations.AlterField(
            model_name='strvvariety',
            name='variety_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 7, 3, 14, 485807)),
        ),
    ]
