# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_auto_20171120_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 12, 8, 20, 564026)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 12, 8, 20, 568970)),
        ),
    ]
