# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_auto_20171120_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dealer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 10, 24, 29, 62974)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 10, 24, 29, 68092)),
        ),
    ]
