# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_auto_20180310_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 12, 29, 52, 247898)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2018, 3, 10, 12, 29, 52, 252961)),
        ),
    ]
