# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_auto_20171105_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='strvvariety',
            name='yield_advantage',
            field=models.CharField(default='hello_y', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 11, 8, 11, 143477)),
        ),
        migrations.AlterField(
            model_name='strvvariety',
            name='duration_in_days',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='strvvariety',
            name='plant_height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='strvvariety',
            name='yield_in_tonne',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 11, 8, 11, 147756)),
        ),
    ]
