# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_auto_20171127_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='STRAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 10, 55, 43, 542906)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dealer_id',
            field=models.ForeignKey(db_column='Dealer_Registration_id', on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration'),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 10, 55, 43, 547914)),
        ),
        migrations.AddField(
            model_name='stravailability',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration'),
        ),
        migrations.AddField(
            model_name='stravailability',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety'),
        ),
    ]
