# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_auto_20171127_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='dealer_id',
            new_name='dealer_shop',
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 12, 11, 22, 355250)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 12, 11, 22, 360247)),
        ),
    ]
