# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_auto_20171127_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerdemand',
            name='dealer',
            field=models.ForeignKey(db_column='Dealer_Registration_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vawdemand',
            name='vaw',
            field=models.ForeignKey(db_column='VAW_Registration_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Masters.VAW_Registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 8, 50, 58, 725059)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 11, 29, 8, 50, 58, 730246)),
        ),
    ]
