# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_auto_20180310_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerdemand',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='dealerdemand',
            name='variety_name',
        ),
        migrations.RemoveField(
            model_name='vawdemand',
            name='variety_name',
        ),
        migrations.RemoveField(
            model_name='vawdemand',
            name='vaw',
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 10, 28, 16, 390280)),
        ),
        migrations.DeleteModel(
            name='DealerDemand',
        ),
        migrations.DeleteModel(
            name='VAWDemand',
        ),
    ]
