# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_auto_20180312_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 10, 28, 29, 506616)),
        ),
    ]
