# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_auto_20171129_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravailability',
            name='shop',
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 12, 48, 1, 564918)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 12, 1, 12, 48, 1, 569931)),
        ),
    ]
