# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_auto_20171201_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='vawdemand',
            name='variety2',
            field=models.CharField(default='sb', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 5, 58, 2, 50453)),
        ),
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2017, 12, 6, 5, 58, 2, 55734)),
        ),
    ]
