# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0013_auto_20180923_1935'),
    ]

    operations = [
    ]
