# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_auto_20180923_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 19, 53, 35, 115186)),
        ),
    ]
