# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0016_auto_20180923_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='strvvariety',
            name='variety_name_oriya',
            field=models.CharField(default='TEST', max_length=255),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 20, 12, 36, 80104)),
        ),
    ]
