# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_auto_20180923_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='strvvariety',
            name='description_oriya',
            field=models.TextField(default='TEST', max_length=650),
        ),
        migrations.AddField(
            model_name='strvvariety',
            name='grain_type_oriya',
            field=models.CharField(default='TEST', max_length=255),
        ),
        migrations.AddField(
            model_name='strvvariety',
            name='suitable_land_type_Oriya',
            field=models.CharField(default='TEST', max_length=200),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 20, 16, 54, 760501)),
        ),
    ]
