# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0010_auto_20180312_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_collected', models.DateField()),
                ('chk', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(db_column='Dealer_Registration_id', on_delete=django.db.models.deletion.CASCADE, to='Masters.Dealer_Registration')),
                ('variety_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety')),
            ],
            options={
                'verbose_name': 'Dealer Demand',
                'verbose_name_plural': 'Dealer Demands',
            },
        ),
        migrations.CreateModel(
            name='VAWDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=255)),
                ('varietyName', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date_collected', models.DateField(default=datetime.datetime(2018, 3, 12, 10, 28, 29, 533161))),
                ('check', models.BooleanField()),
                ('variety_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.STRVVariety')),
                ('vaw', models.ForeignKey(db_column='VAW_Registration_id', on_delete=django.db.models.deletion.CASCADE, to='Masters.VAW_Registration')),
            ],
            options={
                'verbose_name': 'VAW-Demand',
                'verbose_name_plural': 'VAW-Demands',
            },
        ),
    ]
