# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vawdemand',
            name='date_collected',
            field=models.DateField(default=datetime.datetime(2018, 3, 12, 13, 8, 45, 375673)),
        ),
    ]
